
const $=s=>document.querySelector(s);let selected=null;
function esc(s){return (s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function ageLine(p){return [p.nacimiento&&`Nac. ${p.nacimiento}`, p.lugar_nacimiento].filter(Boolean).join(' · ')}
function filtered(){const q=$('#q').value.trim().toLowerCase();const rel=$('#rel').value;return PERSONAS.filter(p=>{let t=Object.values(p).filter(x=>typeof x==='string').join(' ').toLowerCase();return (!q||t.includes(q)) && (!rel||p.relacion===rel)}).sort((a,b)=>a.nombre.localeCompare(b.nombre,'es'));}
function renderList(){const arr=filtered();$('#count').textContent=arr.length;$('#list').innerHTML=arr.map(p=>`<button class="person-btn ${selected===p.id?'active':''}" onclick="show('${p.id}')"><strong>${esc(p.nombre)}</strong><span>${esc(p.relacion||'')}<br>${esc(ageLine(p))}</span></button>`).join('')||'<div class="empty">No hay resultados.</div>';if(!selected&&arr[0])show(arr[0].id,false)}
function linkList(items){return (items||[]).map(x=>`<a href="#" onclick="show('${x.id}');return false">${esc(x.nombre)}</a>`).join('')||'<span class="empty">—</span>'}
function field(label,val){return `<div class="field"><small>${label}</small><div>${esc(val)||'—'}</div></div>`}
function show(id,rerender=true){selected=id;const p=PERSONAS.find(x=>x.id===id);if(!p)return;$('#detail').innerHTML=`<span class="badge">${esc(p.relacion||'Persona incluida')}</span><h2>${esc(p.nombre)}</h2><div class="grid">${field('Nacimiento',p.nacimiento)}${field('Lugar nacimiento',p.lugar_nacimiento)}${field('Defunción',p.defuncion)}${field('Lugar defunción',p.lugar_defuncion)}${field('Profesión',p.profesion)}</div><h3>Familia</h3><div class="links"><b>Padres:</b><br>${linkList(p.padres)}<br><br><b>Cónyuges:</b><br>${linkList(p.conyuges)}<br><br><b>Hijos:</b><br>${linkList(p.hijos)}</div>${p.notas?`<div class="note"><b>Notas</b><br>${esc(p.notas)}</div>`:''}<div class="downloads"><a href="celestina_ibarra_2gen_el_cortijo.csv">Descargar CSV</a><a href="celestina_ibarra_2gen_el_cortijo.ged">Descargar GEDCOM</a></div>`;if(rerender)renderList();}
function init(){document.getElementById('total').textContent=PERSONAS.length;const rels=[...new Set(PERSONAS.map(p=>p.relacion).filter(Boolean))].sort();$('#rel').innerHTML='<option value="">Todas las relaciones</option>'+rels.map(r=>`<option>${esc(r)}</option>`).join('');$('#q').addEventListener('input',()=>{selected=null;renderList()});$('#rel').addEventListener('change',()=>{selected=null;renderList()});renderList();}
init();
